apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-web
  namespace: test
  labels:
    app: frontend-web
spec:
  selector:
    matchLabels:
      app: frontend-web
  template:
    metadata:
      labels:
        app: frontend-web
    spec:
      containers:
      - name: frontend-web
        image: imrenagi/frontend:v0.0.2
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: test
spec:
  selector:
    app: frontend-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080